### ISSUE TITLE
Curator/Monitoring - track resource utilization across projects

### ISSUE THREAD

**Issue by tumido** [operate-first/operations#327]
Colab with Curator/Koku - create dashboards for per cluster/per project resource consumption

cc @durandom @gagansk

**Comment by HumairAK** [comment]
@tumido bump

**Comment by tumido** [comment]
Sure, @durandom's on PTO, feel free to schedule a meeting with me and @HumairAK  :+1:

**Comment by gagansk** [comment]
A [document](https://docs.google.com/document/d/1OTR3N90MUuc9TIrqJ8BmTh9VXBxAdXgR5opyuCmLTOI/edit?usp=sharing) has been created to identify the feature gaps. A PRD will be written for this purpose. We can proceed after @durandom and @hpdempsey are back from PTO.

**Comment by gagansk** [comment]
A new milestone has been created in Curator ([#22](https://github.com/operate-first/curator/milestone/22))for a collab between Curator and Operate First. 

The Curator team presented a demo of Trino and Superset Dashboards in Operate First to @durandom and @hemajv

**Comment by hpdempsey** [comment]
The specific input we are looking for at this stage is what the current Operate First admins think would be useful types of reports (presumably in the form of graphs, tables etc. that we demonstrated with Triino/Superset) to help admins and operators carry out reporting and planing activities for the Operate First clusters.  Curator reports are based on stored data, and so can cover short or long past time periods  (e.g. past day, week or month) and can aggregate various OpenShift API measurements into different types of reports.  We would like input on what (if any) reports we should produce regularly for the current admin group, and how the admins would easily access those reports as part of Operate Firs admin workflows.

**Comment by durandom** [comment]
@HumairAK this should be tied into https://github.com/orgs/operate-first/projects/33
@gagansk the most important information is resource requests (CPU/MEM) per namespace to see the utilization of the environment. Next step would be grouping the namespaces by "team". E.g. ODH requests 33%.

**Comment by HumairAK** [comment]
yeah we went over some of our existing tools to monitor these items with @leihchen, some examples of current grafana dashboards we use for cpu/mem monitoring: 
- [cpu overview](https://grafana.operate-first.cloud/d/nA4fwtvnzzdf3e/cluster-cpu-overview?orgId=1)
- [memory moverview](https://grafana.operate-first.cloud/d/ucHWsaF7i/cluster-memory-overview?orgId=1&var-datasource=openshift-monitoring&var-cluster=moc%2Fsmaug)

**Comment by hpdempsey** [comment]
We are already doing the type of reports suggested by @durandom, but we will polish them up a bit and make them easier to find for the OF ops folks.  We are not trying to duplicate the Grafana dashboards.
