### ISSUE TITLE
Post alert when certificate is about to expire

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#331]
It would be nice to get an alert when the api server certificate is about to expire. We need to either determine if there is an existing metric we can use, or if not, how to expose a new metric to openshfit prometheus, and then ensure there is an appropriate alert configuration for it.

**Comment by larsks** [comment]
@4n4nd identified [this metric](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22openshift-monitoring%22,%7B%22expr%22:%22apiserver_client_certificate_expiration_seconds_count%7Bapiserver%3D%5C%22kube-apiserver%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D), which from its name ("apiserver_client_certificate_expiration_seconds_count") seems relevant, but if you look at the metric values it doesn't seem immediately obvious what it's counting.

**Comment by larsks** [comment]
There is some indication that metric is just for client certificates, and isn't relevant to detecting server certificate expiration.

**Comment by larsks** [comment]
I've opened https://access.redhat.com/support/cases/#/case/02958692 with this question.

**Comment by larsks** [comment]
And the resolution is "you can't do that":

> So unfortunately as I sync up with monitoring team in engineering this morning to test my proposed custom alert, I'm advised that this is not currently supported as per the OCP documentation.
> 
> When I asked them about creating a Request for Enhancement (RFE) they pointed me to this one: Allow/Support custom Prometheus alerts that has been open for some time now. Looks like it's "Status: Accepted" but "Resolution: Unresolved".
> 
> I will be attaching this case to help them prioritize this higher up; so we will have to wait for this RFE to progress before we're able to make any custom alerts that are supported currently.
> 
> Apologies for any inconvenience this may cause. It might also help to get your account team involved to help push this feature along.

**Comment by 4n4nd** [comment]
until then we could set a calendar reminder

**Comment by tumido** [comment]
seems like we can influence downstream Openshift RFEs now! Good job! :slightly_smiling_face: 

cc @durandom see https://access.redhat.com/support/cases/#/case/02958692

Btw, the workaround hinted in the last comment seems like a good one. We probably should try implementing it:

quote from Noreen Carmichael:
> As a very last resort you could create a custom alert to monitor kube-apiserver-to-kubelet-signer certificate expiration via cronjob (an example below - please keep in mind this is not supported but simply a temporary workaround):
>
> ```
> $ cat << EOF > kube-checker-cronjob.yaml
> apiVersion: batch/v1beta1
> kind: CronJob
> metadata:
>   creationTimestamp: null
>   name: kube-checker
>   namespace: openshift-monitoring
> spec:
>   jobTemplate:
>     metadata:
>       creationTimestamp: null
>       name: kube-checker
>     spec:
>       template:
>         metadata:
>           creationTimestamp: null
>         spec:
>           containers:
>           - command:
>             - bash
>             - -c
>             - 'EXP=$(oc get secret kube-apiserver-to-kubelet-signer -n openshift-kube-apiserver-operator
>               -o jsonpath="{.metadata.annotations.auth\.openshift\.io/certificate-not-after}")
>               && DATE=$(date --iso-8601) && DAYS=$(( ($(date -d ${EXP} +%s) - $(date
>               -d ${DATE} +%s)) / 86400 )); [[ ${DAYS} -gt 0 && ${DAYS} -lt 120 ]]
>               && echo -ne "apiVersion: monitoring.coreos.com/v1\nkind: PrometheusRule\nmetadata:\n  name:
>               kubelet-signer-alert\n  namespace: openshift-monitoring\nspec:\n  groups:\n  -
>               name: example\n    rules:\n    - alert: KubeClientCertificateExpirationCustom\n      annotations:
>               \n        message: kube-apiserver-to-kubelet-signer certificate is expiring in less than 4 months at ${EXP}
>               (please note that automated renewal is approximately 73 days before that date).\n      expr: |
>               \n        vector(1)\n      labels:\n        severity: warning\n"
>               | oc create -f - || oc delete PrometheusRule kubelet-signer-alert -n openshift-monitoring; exit 0'
>             image: registry.redhat.io/openshift4/ose-cli:latest
>             name: kube-checker
>             resources: {}
>             terminationMessagePath: /dev/termination-log
>             terminationMessagePolicy: File
>           dnsPolicy: ClusterFirst
>           restartPolicy: OnFailure
>           schedulerName: default-scheduler
>           securityContext: {}
>           serviceAccount: prometheus-operator
>           serviceAccountName: prometheus-operator
>           terminationGracePeriodSeconds: 30
>   schedule: '@daily'
> status: {}
> EOF
> 
> $ oc create -f kube-checker-cronjob.yaml
> ```
>
> NOTE_1: Please adapt accordingly the schedule and all the necessary variables in the above code, but please remember to keep the names homogeneous, the proper indentation in place and single/double quotes as they are above.
> 
> NOTE_2: The embedded script within the cronjob will create or remove the custom PrometheusRule as necessary based on its previous existence and the logic [[ ${DAYS} -gt 0 && ${DAYS} -lt 120 ]].
> 
> How to check the CronJob status:
> 
> ```
> $ oc get cronjob kube-checker -n openshift-monitoring
> NAME           SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
> kube-checker   @daily     False     0        115s            2m19s
> ```
> How to check the custom PrometheusRule content (when present):
> 
> ```
> $ oc get PrometheusRule kubelet-signer-alert -n openshift-monitoring -o yaml
> apiVersion: monitoring.coreos.com/v1
> kind: PrometheusRule
> metadata:
>   creationTimestamp: "2020-12-18T08:56:16Z"
>   generation: 1
>   managedFields:
>   - apiVersion: monitoring.coreos.com/v1
>     fieldsType: FieldsV1
>     fieldsV1:
>       f:spec:
>         .: {}
>         f:groups: {}
>     manager: kubectl-create
>     operation: Update
>     time: "2020-12-18T08:56:16Z"
>   name: kubelet-signer-alert
>   namespace: openshift-monitoring
>   resourceVersion: "798549"
>   selfLink: /apis/monitoring.coreos.com/v1/namespaces/openshift-monitoring/prometheusrules/kubelet-signer-alert
>   uid: a2c597f1-3fb9-43f7-9c8a-c71b169d5b56
> spec:
>   groups:
>   - name: example
>     rules:
>     - alert: KubeClientCertificateExpirationCustom
>       annotations:
>         message: kube-apiserver-to-kubelet-signer certificate is expiring in less than 4 months at 2021-12-16T11:34:38Z (please note that automated renewal is approximately 73 days before that date).
>       expr: |
>         vector(1)
>       labels:
>         severity: warning
> ```
