### ISSUE TITLE
Create an warning alert for possible CPU overcommit in case of node outage  

### ISSUE THREAD

**Issue by tumido** [operate-first/operations#350]
On baremetal installs we don't have that much options on how to add/remove new nodes on demand.

In case of a node outage/drain we need to be able to migrate all the workloads running on affected node (any) to other nodes. That means the other nodes has to have remaining free capacity of cpu/memory resources to be able to accommodate these drained workloads. An alert should be fired if we overcommit the resources and use the cluster nodes in a way that the remaining free space would not be enough for these workloads.

Acceptance criteria:
- New `PrometheusRule` resource stored at `cluster-scope/base/monitoring.coreos.com/prometheusalerts` in the apps repo
- Deploys to `openshift-monitoring` namespace (question: is it necessary, I need help on this) 
- It fires alert when the total sum of requested resources (for each of CPU, memory) on the whole cluster exceeds sum of all available resources on the cluster subtracted by the largest node
- Should disregard master nodes and workloads on master nodes, since those are not schedulable to user workloads

**Comment by tumido** [comment]
Related to: https://github.com/operate-first/SRE/issues/346#issuecomment-875643058

**Comment by hpdempsey** [comment]
Dani is planning to look into this issue.
