### ISSUE TITLE
Add an ability to automatically assign issues based on github labels

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#353]
As per the goal of https://github.com/orgs/operate-first/projects/26 we need the ability to be able to assign members to issues based on github labels. 

There is a lot of room for how we can implement this and I am open to suggestions. The solution should complement the solution [here](https://github.com/operate-first/SRE/issues/349) so that we may be able to assign individuals to the appropriate alerts. 

However, the solution can also work as a generic solution for multiple repositories.

Let's take an example: 

Suppose that an alert is fired for Jupyterhub in the alerts repo. The solution implemented [here](https://github.com/operate-first/SRE/issues/349) will add a `jupyterhub` label. The solution implemented for _this_ task, should then assign OR @mention all the right candidates to the alert issue. 

Some questions to consider: 

1. Should people be assigned or just @mentioned ?
I think an argument can be made for @mention only because, assigning implies the individual is now responsible for handling this issue, while there may be people that are simply interested in following along with such labels. 

2. How do we determine who gets notified on what label? 
Whatever the solution, it needs to be declarative, i.e. we need to be able to store this info in git. It should be a simple enough sort of config that allows people to just make a simple PR if they want to follow and be notified upon a particular label within a repo or this org.

3. What tool should we use? 
I'm going to leave this one open, but @tumido has mentioned Prow [external-plugins](https://github.com/kubernetes/test-infra/tree/master/prow/plugins#external-plugins). We already have prow deployed, so it should just be a matter of writing this external plugin (the link offers examples) and handle the webhook event accordingly.

**Comment by HumairAK** [comment]
@PARTHSONI95 will be working on this after [this](https://github.com/operate-first/SRE/issues/349) is complete. 

But let's get everyone a chance to chime in and offer their suggestions/opinions etc. 

@tumido @4n4nd  and whoever else.

**Comment by HumairAK** [comment]
@harshad16 as well, figured you might have some insight suggestions here as well :)

**Comment by 4n4nd** [comment]
I think this is a great path forward :+1: 

1. I think we should have someone to assign the issue to, this person will be responsible for this issue, or this person will assign the person who is responsible.
2.  I think we can add a simple config file in the alerts repo:
```yaml
label_config:
  label-name:
    - assignee1
    - assignee2
  service/jupyterhub:
    - 4n4nd
    - HumairAK
```
3. For the tools, do you it's better if we extend the existing tooling that thoth has (sesheta)? or we could create a separate application that does this where @PARTHSONI95 wanted to make the assignment decisions based on some AI.
