### ISSUE TITLE
Give lars access to shared bitwarden

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#376]
I would like access to the shared bitwarden instance created via https://github.com/operate-first/SRE/issues/363 so that I can put the kubeadmin passwords there for the smaug, zero, and infra clusters. I'm not currently a member of the [operate-first group](https://rover.redhat.com/groups/group/operate-first), and I'm not sure how to access bitwarden once the group membership is arranged.

**Comment by HumairAK** [comment]
@larsks was added the operate-first ldap group, which alotted him access to the operate-first bitwarden collection.
