### ISSUE TITLE
How should we handle resourcequotas for namespaces when they differ from cluster to cluster? 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#392]
Currently resource quotas are cloud-wide, this keeps things simple but gives us less flexibility when we need different quotas for similar namespace deployments. E.x. `opf-jupyterhub` one clusterA may not need as many resources as `opf-jupyterhub` on clusterB.

I think just adding overlays, and patching over quotas is the easiest way to do this. But if someone has a more intelligent / cleaner solution I'm all ears.

**Comment by HumairAK** [comment]
@tumido @4n4nd

**Comment by tumido** [comment]
I think in the case of quotas we're pushing the Kustomize patterns to its limits, with all those components stuff etc. So.. I don't know.

It may also make sense to have a different name for the namespace in such case...

I think patching it make sense if we want to keep following the current layout. That makes the most sense to me.

**Comment by HumairAK** [comment]
closing in favor of: https://github.com/operate-first/apps/issues/1849
