### ISSUE TITLE
Keycloak log reporting errors for duplicate key value violations

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#393]
More specifically: 
```
ERROR: duplicate key value violates unique constraint "uk_b71cjlbenv945rb6gcon438at"
  Detail: Key (realm_id, client_id)=(operate-first, smaug) already exists.
```

Found here: https://console-openshift-console.apps.moc-infra.massopen.cloud/k8s/ns/keycloak/pods/keycloak-0/logs

**Comment by tumido** [comment]
Not sure this has any solution on our end. We can report it upstream if we can reproduce it.
