### ISSUE TITLE
Centralizing Markdown Docs from apps, support, sre, etc. 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#413]
I understand that there's Hitchhiker's guide and community-handbook etc. underway, but I think for a more immediate solution to access and maintain docs, we can just migrate all our docs to the `apps` repo. I'm talking about docs in the following locations: 

- [runbooks](https://github.com/operate-first/SRE/tree/master/runbooks) 
- [support docs](https://github.com/operate-first/support/tree/main/docs) 

The docs in these locations require you to interact with the `apps` repo, so often times we are updating the `apps` repo then need to update these repos, which creates overhead in adding new docs and discourages people from doing so. 

By keeping them in the same repo, we can also enforce others, when they make new prs, to also update the docs within the same pr, making docs easier to maintain. 

I'd like to move these to the `apps` repo [here](https://github.com/operate-first/apps/tree/master/docs), and re-organize them so they are easier to understand/consume, and reflect these changes on the website. 

This would be a relatively easy change to help us continue to document more items easily whilst others work towards adding hitchhiker notebooks/community handbooks etc. WDYT?

**Comment by tumido** [comment]
What about we move them directly to Hitchhiker's guide as is, and then slowly work on converting the Markdowns to Notebooks? I understand the multi-repo troubles, but I'm not sure if it's helping much.. if the docs still eventually ends up in Hitchhiker's guide, it means they will be in a different repo anyways. So why not do it right away?

@durandom WDYT?

**Comment by durandom** [comment]
How often does a change to `docs` and `apps` happen at the same time?
For simplicity I would also move them to the hitchhikers guide. 

And btw, there's no need to have it all as JupyterNotebooks. If it's just a markdown, it's just a markdown :)

**Comment by HumairAK** [comment]
> How often does a change to docs and apps happen at the same time?
> For simplicity I would also move them to the hitchhikers guide.

In this case it would be all the docs that directly involve interacting with the `apps` repo, I would like them in the `apps` repo because then we can enforce users to update docs in the _same_ pr that is often introducing the change which need to be reflected in documentation as well. It also becomes easier to request additional new docs be added within the same PR.

**Comment by 4n4nd** [comment]
>  then slowly work on converting the Markdowns to Notebooks?

I am not sure if I like that. Reviewing notebooks is not as straightforward as reviewing a md file and this makes reviewing a PR very slow.  Not only that, if we are planning to offload making PRs to users, writing notebooks instead of mds will only discourage the users since you need to set up an environment to be able to make changes to a notebook.

> I would like them in the apps repo because then we can enforce users to update docs in the same pr that is often introducing the change which need to be reflected in documentation as well. It also becomes easier to request additional new docs be added within the same PR.

I :100: agree with this and I think this should be one of the main reasons for centralizing docs.

**Comment by HumairAK** [comment]
To the point of pr reviews, @durandom pointed me to this: https://www.reviewnb.com/ which we should look into. 

But I still want the markdowns in the apps repo. This is my suggestion: 
- notebooks in hitchhiker's repo
- markdowns in apps repo 

Link the markdown docs in the hitchhiker's repo to the apps repo. 

The docs remain decentralized, but this is different from our current situation, wherein it's 100% clear only notebooks go in hitchikers repo, everything else goes in apps repo. Also, we aggregate them all together on the website.

**Comment by HumairAK** [comment]
I think we're in a good place with the current jupyterbook gitopsdocs setup, and the consolidation of repos etc. Closing. Please re-open if there's more to do/discuss here.
