### ISSUE TITLE
Arrange for periodic snapshot of Noobaa database

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#431]
## Background

[Noobaa][] provides our OpenShift environments with an object storage API (similar to Amazon [S3][]).  After a recent power interruption, the database that backs the Noobaa instance on Smaug became corrupt, and we ultimately had to discard all our object storage buckets and start from scratch.

[noobaa]: https://noobaa.io
[s3]: https://aws.amazon.com/s3/

## Task

Install [snapscheduler](https://backube.github.io/snapscheduler/), which is designed for exactly this purpose, and then create the necessary resources to create daily snapshots of the Noobaa database PVC with a 1 week retention time. 

The Noobaa database PVC can be found in the `openshift-storage` namespace:

```
$ oc -n openshift-storage get pvc oc -n openshift-storage get pvc
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                           AGE
db-noobaa-db-pg-0   Bound    pvc-df916dc5-56ba-4566-a335-de51a42a01c1   50Gi       RWO            ocs-external-storagecluster-ceph-rbd   41d
```

**Comment by margarethaley** [comment]
@larsks quick question: if there are two versions of the operator available on OperatorHub (one of which is a community operator), which do you normally go with?
