### ISSUE TITLE
Explore ACM + Identitatem as a solution to centralized sso/identity management for op1st cloud

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#432]
We should try to identify a cluster with users that can serve as a candidate for trying out [identitatem](https://identitatem.github.io/idp-mgmt-docs/).

This would mean likely moving away from keycloak to handle our access control, and delegating access managment to ACM instead. 

ACM devs have offered to lend us a helping hand with installing/setting up Identitatem, and also are looking for feedback on the process. 

Couple of caveats: 
- OCP cluster needs to be 4.8.12+ and 4.9+ is not supported yet, this should come in a future patch update. Though we can work around this by using an upstream build, which requires us to install the operator manually. Waiting to hear back from ACM team on the feasibility of this.
- Upgrades _may_ not be supported for tech preview, we're waiting to hear back on this from the ACM team
- This would require pulling identified cluster from Keycloak and having acm manage access for it directly via identitatem. 

I think we should first bring it out to a cluster like rick, or balrog. Once it proves stable, and without issues, we can roll it out to all clusters, wdyt?

**Comment by HumairAK** [comment]
@durandom

**Comment by durandom** [comment]
Before we start, should we create a WIP PR to blueprint that has the reasoning for diverting from:

https://github.com/operate-first/blueprint/blob/main/adr/0017-authentication-for-platform.md
https://github.com/operate-first/blueprint/blob/main/adr/0018-migration-to-keycloak.md

Or a PR to these existing ADRs (which would be a first, I guess)

**Comment by HumairAK** [comment]
identitatem is set up, go to https://github.com/operate-first/support/issues/557 for switching rest of the clusters story.
