### ISSUE TITLE
moc-infra unable to reach nfs server

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#437]
The moc-infra is unable to reach the NFS server. The controller in the `democratic-csi` namespace is timing out trying to connect using ssh:

```
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: Error: Timed out while waiting for handshake","service":"democratic-csi"}
{ code: 13, message: 'Error: Timed out while waiting for handshake' }
```

This looks like the same issue we encountered previously on smaug in https://access.redhat.com/support/cases/#/case/03038089 (see  https://bugzilla.redhat.com/show_bug.cgi?id=1996108 for the related bz).

The solution is either:

1. Enable local gateway mode, which may or may not be possible on an existing cluster (there are only docs for making this configuration as part of a fresh install or ugprade).
2. Roll back to OpenShiftSDN (which is what we did with Smaug)

**Comment by HumairAK** [comment]
Let's roll back then? (1.) seems like there's a lot of uncertainty there. At least with (2.) we'll be consistent. wdyt?

**Comment by larsks** [comment]
I would like to wait and see what the answer is to my question on the bz (or the same posted to the `openshift-sme` mailing list). If we don't hear anything tomorrow, we can plan on going ahead with the rollback in any case.

**Comment by larsks** [comment]
Here's the answer I received in chat:

> If the customer's desire is to be on  4.8 then I would suggest going to openshiftSDN if they need to be able to leverage the kernel routing stack. If they can wait to upgrade, then I would prefer that route and hopefully in jan we will have the bug resolved. In 4.10 a new API is exposed: https://github.com/openshift/api/pull/1033/files#diff-4e4e6281ba1d97ce87d29c6a9fa1961cf4605b792baf2ec44f09796164dc4a14R300

**Comment by HumairAK** [comment]
I mean our desire is not to be on 4.8, but our auth is dependent on the nfs server, if we can remove that dependency, then I suppose we can wait. So after the holidays I suggest we do that, and opt for the wait option. @larsks I believe you suggested using a different csi driver to use host mounts directly, maybe we can spin off a new issue for that to reduce reliance on nfs.

**Comment by larsks** [comment]
...or just use the OpenShiftSDN driver, of course. But I agree, this is something for January.
