### ISSUE TITLE
Create a diagram or offer a link/explanation elaborating on cpu requests/limits vs capacity during project onboarding

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#439]
For new comers it's not always obvious what the differences between cpu limits/requests are, and how much of each they ought to request for their projects. We should offer some further clarification via visualization, or link to further reading so they may make an informed decision on the matter, and request the amounts suitable for their project.

**Comment by durandom** [comment]
This is super important, we need to know what's consuming how much and where

**Comment by HumairAK** [comment]
@durandom that we already have to some extent: 

CPU: 
https://grafana.operate-first.cloud/d/nA4fwtvnzzdf3e/cluster-cpu-overview?orgId=1&from=now-1h&to=now&var-datasource=moc-smaug&var-cluster=moc%2Fsmaug

Memory: 
https://grafana.operate-first.cloud/d/ucHWsaF7i/cluster-memory-overview?orgId=1&var-datasource=moc-smaug&var-cluster=moc%2Fsmaug

**Comment by mubariskhan96** [comment]
[This](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits) link seems to be doing a good job at explaining. What do you think? @HumairAK

**Comment by HumairAK** [comment]
@mubariskhan96 I'm good with that, next step is to identify the area where it's most fruitful to inform users a bout this. I'm thinking the project onboarding docs: 

Under "Namespace Quota" [here](https://github.com/operate-first/support/blob/main/.github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml) maybe? 

Or the qutoas doc where it links to? Which I just realized is broken (ugh), it ought to link here: https://www.operate-first.cloud/apps/content/cluster-scope/quotas.html

**Comment by durandom** [comment]
@mubariskhan96 do you want to try a PR to update the quota docs with the link?

https://github.com/operate-first/apps/blob/master/docs/content/cluster-scope/quotas.md

**Comment by mubariskhan96** [comment]
Sounds good! I will open a PR to update it here https://github.com/operate-first/apps/blob/master/docs/content/cluster-scope/quotas.md
