### ISSUE TITLE
Let's make Grafana landing page more friendly

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#440]
The landing page at https://grafana.operate-first.cloud/ is just the Grafana default. Let's replace that with something that highlights interesting dashboards, or maybe provides information about how to contribute new dashboards (or links to appropriate docs), etc.

**Comment by bryanmontalvan** [comment]
I've figured out how to edit the panels on the home dashboard, however, as we discussed this is only a live change and not one being saved behind the scenes (e.g, if everything is teared down the changes would not be saved). In preparation to getting that part I would like prompt the following questions

**Q1:** What links do you recommend should be added to the landing page?

**Q2:** Do you have a vision or idea for what these _interesting highlights_ may be?

**Comment by 4n4nd** [comment]
@larsks we do have some of the docs published [here](https://www.operate-first.cloud/apps/content/grafana/README.html). Do you think https://grafana.operate-first.cloud/ should point to these docs instead?

**Comment by bryanmontalvan** [comment]
The docs are great for learning how to contribute to the dashboards and great links to learn more about software. My only issue is that the goal here is to modify the landing page not adding a new dashboard to the Operate First grafana. A very specific problem which is understandable as to why it is not on the docs.

My question now, is the home dashboard(landing page) modifiable through the code base or only through the dashboard's website? Currently I cannot find the landing page via the source code but if it is in fact there a link would be kindly appreciated, thanks!

**Comment by larsks** [comment]
@4n4nd I think it would be great if the grafana landing page linked to the existing operate-first docs dealing with grafana, yes. I wasn't proposing writing new ones, just that we make things as discoverable as possible.

@bryanmontalvan 

> My question now, is the home dashboard(landing page) modifiable through the code base or only through the dashboard's website?

In theory you should be able to create a new dashboard following [the docs](https://www.operate-first.cloud/apps/content/grafana/README.html) by creating a new `GrafanaDashboard` object; I assume there's a mechanism for making the dashboard the default, but Anand can probably help with that.

> Q2: Do you have a vision or idea for what these interesting highlights may be?

What I would love to see on the landing page would be some sort of top-level cluster statistics for all of the managed clusters (like memory/cpu used vs available, number of pods, etc).  Basically a high level summary of what's available in the cluster management dashboards https://grafana.operate-first.cloud/dashboards/f/XhHHmTT7z/cluster-management.

Perhaps along with each cluster should be a link to the cluster overview page.

**Comment by bryanmontalvan** [comment]
@larsks 
This is what I have so far for the new home page, I was wondering if I should add anything else. I took the most important panels from each Overview dashboard and compiled they here.

I was thinking maybe to fill in the space for each row, add a text panel with docs or references to understand more what the graphs/panels are detailing?

Live Link:
https://grafana.operate-first.cloud/d/-MbVHvxnz/welcome-info?orgId=1

**Comment by larsks** [comment]
The way it's implemented right now, the dashboard only shows information for a single cluster at at a time. What I was proposing was something that shows an overview of *all* clusters.  E.g., for the "Cluster Memory Overview" row, have a series of pie charts, one per cluster, show free memory vs available memory (and so forth for cpu resources, workloads, etc).

**Comment by bryanmontalvan** [comment]
@larsks Hey Lars, I made some updates I was wondering if I'm heading in the right direction.
Let me know if I should remove, add, or replace anything. Thanks!

Link: [Welcome Info Dashboard](https://grafana.operate-first.cloud/d/-MbVHvxnz/welcome-info?orgId=1&from=1643135139252&to=1643136039252&var-datasource=default&var-cluster=emea%2Fbalrog)

### Updates
`General`
- Removed variable for specific cluster and namespace

`Cluster CPU Overview`
- Shows each clusters total core count (divided by master and worker)
- Shows combined total cores
- Bar gauge representing its each individual clusters free cores
- Pie charts representing combined free cores (divided in master and worker)

`Cluster Memory Overview`
- Similar to *Cluster CPU row*, shows individual total memory counts along with total combined space
- Bar gauges representing total free memory (divided in master and worker)
- Added series of pie charts, one per each luster. Representing available memory vs free memory

`Cluster Pod Overview`
- A pie chart for each cluster representing pods aggregated by Phase

`Cluster Storage Overview`
- Pie charts for each cluster, showing PVC's by namespace

**Comment by larsks** [comment]
I think that's a lot more like I envisioned. There are a few changes I would suggest:

- Replace `master` with `controller` (see e.g. https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language)
- I would try to reduce the number of panels. E.g, for the cluster CPU overview, maybe we can have a single panel for each cluster showing available vs. total cores. (And similar for memory)
- The bar gauges for core count might be nice for that, but I think they're currently reversed (we probably want to show "cores in use" so that "bigger bar" == "more load on the cluster" (and we would probably want the color gradient to match, so "more red" == "more load on the cluster")

@HumairAK @4n4nd do either of you folks have input on this?

**Comment by HumairAK** [comment]
I agree with @larsks on reducing the number of panels, I think the cpu/memory overview should be minimal to give a general idea at a quick glance on the state of the cloud. A single panel for each cluster is sufficient. 

I would also encourage you to dynamically general queries and panels based on the `cluster` label. If you manually create a panel for each cluster for instance, then everytime we add a new cluster we have to update the dashboard. But if you use something like "Panel options > repeat options" and use a variable to iterate the panel over, the panels can be dynamicaly generated for each cluster. 

For queries, you can do the same by introducing a wild card, for example something like: 

```
cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io="master"}

```
Can be converted to: 
```
sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io="master"}) by (cluster)
```

And if you set the datasource as `thanos-frontend` (aggregate of all clusters' metrics), with the legend as `{{ cluster}}` -- you will see the values generated dynamically for _that_ panel. 

Of course if you're just reducing the chart to 1 panel per cluster (with presumably 1 query for that panel), then this last suggestion does not apply (which is for queries within the panels).

**Comment by bryanmontalvan** [comment]
@larsks @HumairAK 
I did some more changes, I wanted to get both of your input again to make sure I'm headed in the right direction. Thanks!

Link: https://grafana.operate-first.cloud/d/-MbVHvxnz/welcome-page?orgId=1

`Changes:`
> I agree with @larsks on reducing the number of panels,
- Reduced panels on Memory and CPU overview to 6 per row

> I would also encourage you to dynamically general queries and panels based on the cluster label
- Partially made dynamic queries for the bar gauges (currently having issues on setting individual maxes for each cluster point)

> But I think they're currently reversed (we probably want to show "cores in use" so that "bigger bar" == "more load on the cluster" 
- Bar gauges on both CPU & Memory Overview now show the requested change("bigger bar equals more load")

`To-do`
- Finish dynamically generated query implementation, creating the variable for dynamic `panel repeats`
- Remove moc/infra from both CPU & Memory Overview `bar gauge` panels

**Comment by hpdempsey** [comment]
Can you make the login page include some text that distinguishes it as an Operate First Grafana instead of generic Grafana too?

**Comment by hpdempsey** [comment]
Also, I agree on fewer panels.  You want the page to start quickly and have only the high-level info.

**Comment by bryanmontalvan** [comment]
@hpdempsey Thanks for the feedback Heidi, after some digging I'm not quite sure changing the `login page` on grafana is possible. I've seen some articles on how to changes images but that's on local environments. 

> Also, I agree on fewer panels. You want the page to start quickly and have only the high-level info.

I'm a bit confused as to how many panels that shown been shown. Do you mean there's too many panels in each row(CPU Overview, Memory Overview, etc..)? Or if there's many panels vertically? Since I understand its tedious to scroll down to view every detail. So I could decrease the panels size and put them into one continuous row, or decrease the panels to 4 per row/section?

 A bit more clarity would be helpful! Thanks :)

**Comment by HumairAK** [comment]
Another suggestion can we include somewhere that mentions that grafana reboots frequently and anyone working on it should back up *frequently* their dashboards in json. And maybe short instruction on where to go to do that.

**Comment by bryanmontalvan** [comment]
@HumairAK I was thinking of having the note in the `Welcome Text Panel` saying *"Note: Grafana is frequently rebooted..."* and having it link to our Grafana doc. Then adding a section that explains how to export/back-up your dashboards? Or do you think its better to have the explanation in the dashboard itself?

**Comment by larsks** [comment]
@bryanmontalvan it is better to put the explanation in the docs ("Learn how to save your grafana dashboard `<here>`...")
