### ISSUE TITLE
Introduce burn-rate based alerts for JupyterHub

### ISSUE THREAD

**Issue by anishasthana** [operate-first/operations#444]
This is a rewrite of #129 to make it easier to parse :-)

### Background

[Prometheus](https://prometheus.io/) is de-facto standard for monitoring applications in the cloud native space. One of the core conceits here is the idea of "time-series" data (look at the Prometheus docs to get a better idea) for metrics. At a high level, you can just think of it as a continues series of values for some given "metric" over a long period of time.

### Task

We already have a lot of metrics we are scraping for Jupyterhub, and we have already defined [SLIs](https://sre.google/sre-book/service-level-objectives/) (Service Level Indicators), Service Level Objectives (SLOs) , and alerts for JupyterHub as part of the Red Hat OpenShift Data Science (RHODS) initiative.

* Find the alerts defined in https://github.com/red-hat-data-services/odh-deployer and use them to help define alerts for the JupyterHub that is deployed in the Operate-First environment
* For bonus points, you can try raising a pull request to upstream [Open Data Hub](https://github.com/opendatahub-io/odh-manifests) so that these alerts can be used by _everyone_ in the community
* An interesting follow-on task to this would be to create a [Grafana](https://grafana.com/) dashboard to graph these metrics over time.

**Comment by anishasthana** [comment]
@4n4nd  and myself can help with any questions you come up with / problems you run in to!

**Comment by mubariskhan96** [comment]
This seems like a very interesting issue to me! And is very closely related to my [co-op project](https://github.com/operate-first/SRE/issues/446).  But, I'm working on some other tasks, and I wont be able to start working on this issue till the next couple of days!

**Comment by hpdempsey** [comment]
Where are the SLIs, SLOs defined for RHODS @anishasthana ?

**Comment by anishasthana** [comment]
https://docs.google.com/document/d/1YsVYg5ZIdLYBKLxU4iEpt4e_KykE8C8nJD2SEFg52eY/edit#heading=h.ladzjqxgg5eo has more information. The actual implemented alerts can be found in https://github.com/red-hat-data-services/odh-deployer

**Comment by mubariskhan96** [comment]
I'm getting started with this task now. But before jumping into writing code, I want to ask some clarifying questions to make sure I'm doing the right thing. 

1. To find out the alerts, in ODH-Deployer, I'm looking at this file: [https://github.com/red-hat-data-services/odh-deployer/blob/main/monitoring/prometheus/prometheus.yaml](https://github.com/red-hat-data-services/odh-deployer/blob/main/monitoring/prometheus/prometheus.yaml ). I checked other files and I could see that this is the only file where the alerts are defined for Jupyter hub. 
2 And now, coming to the Operate First side of things, I would need to create a serviceMonitor.yaml file in this directory [https://github.com/operate-first/apps/tree/master/jupyterhub-idle-culler/base](https://github.com/operate-first/apps/tree/master/jupyterhub-idle-culler/base) and copy the alerts from the ODH-Deployer into it. 


@anishasthana am i on the right track? Thanks!

**Comment by anishasthana** [comment]
The alerts would not go into the culler, there should be a better location for them to go :-)
