### ISSUE TITLE
Co-op Project Idea, looking for feedback and insight

### ISSUE THREAD

**Issue by bryanmontalvan** [operate-first/operations#445]
# Update
#### More detailed proposal here
https://github.com/bryanmontalvan/opf-storage-project

## Introduction
Since I will be working in a storage product group in the summer I've been tasked to come up with a project idea related to storage. And since I am doing SRE work, my project idea will revolve around monitoring.

## The Idea
My co-op project will essentially be, expanding the way we currently monitor storage metrics. With the emphasis on creating understandable and useful data visualizations for users to better understand how their deployment storage is being used. In this context I'll be using Grafana to create such dashboards, and rest of the workflow is still in the research phase.

A complimentary idea, would be to create a `Predictable Consumption Model` which can predict when a PV will be full. And could also forecast other storage related metrics/occurrences

### Feedback
I would like to ask you to all if you had any insight or thoughts about my project idea. 
If you do agree with it I would appreciate any resources or offers to meet 1on1; or guidance.
If you disagree feel free to let me know why, and if you have any alternative ideas that'd be great appreciated as well!

### Thinking
At the moment I am unsure as to where to look at to get this data whether it be from ceph or from ODF directly, so any guidance would be great in this topic. 

## Work
- [ ] Draft storage monitoring dashboard
- [ ] Complete storage monitoring dashboard
- [ ] Draft Predictable Consumption Model
- [ ] Complete PCM

**Comment by chauhankaranraj** [comment]
Hi @bryanmontalvan, this project idea sounds quite interesting! Here's my 2 cents

> improving the way we currently monitor storage metrics. With the emphasis on creating understandable and useful data visualizations for users to better understand how their deployment storage is being used.

I'm not sure if you're familiar with this, but the Ceph team has created some public [telemetry dashboards](https://ceph.io/en/news/blog/2020/public-telemetry-dashboards). Maybe this could provide some inspiration / guidance on what metrics could be some interesting to visualize?

> rest of the workflow is still in the research phase.

One idea could be, to visualize the "disk failure prediction" for the hard disks in the storage cluster, using some ML models we created [here](https://github.com/aicoe-aiops/disk-health-predictor).

> create a Predictable Consumption Model which can predict when a PV will be full. And could also forecast other storage related metrics/occurrences

If you're looking for resources on doing time series forecasting with prometheus metrics, you could check out [this](https://aicoe-aiops.github.io/time-series/README.html) jupyterbook created by our team.
(/cc @Shreyanand)

Hope this helps!

**Comment by bryanmontalvan** [comment]
Hey @chauhankaranraj, thank you so much your feedback is really helpful!
I'l take a look to all the resources you've shared with me!

**Comment by HumairAK** [comment]
> to better understand how their deployment storage is being used.

Not sure I understand what this entails. I think it might be more helpful to add more specifics. In my mind, data/visuals that pertain to the health/state of storage services/resources would be very useful. Basically if an SRE is looking at it, we should be able to help answer some questions like: 

1) "Is our storage layer in good health?"  (Also, what does it mean to be in "good" health?)
2) "If we are not in good health, how bad is it? What component is failing?"
3) "Do we have sufficient resources to meet our users' needs?" 

Given that the actual storage hardware is not operated/managed by us, and we are often limited to what metrics we expose -- we may not be able to answer all questions to satisfaction, but anything that gets us closer is a plus.

**Comment by HumairAK** [comment]
@larsks may also have additional insight here as he has been most involved with the storage components on `smaug/infra/etc.`.

**Comment by larsks** [comment]
My only feedback w/r/t storage is to note that we don't actually manage the underlying storage -- at least in the smaug cluster -- which may have implications for what data we can collect. Broadly, I think providing a storage-focused dashboard is a good idea, and I like the idea of a predictable consumption model that could alert users in advance when they may need to expand their storage allocation.

**Comment by hpdempsey** [comment]
I agree that the storage-focused dashboard and a model to alert users about approaching storage limits would be great to have!   After discussing with Bryan, we agreed he should work on the dashboard first (including looking into what dashboards are already available elsewhere).  We have some people from the Red Hat storage group who are also willing to advise.  Probably a good idea to introduce Bryan to the people who DO manage the Smaug storage as a first step.

**Comment by larsks** [comment]
> Probably a good idea to introduce Bryan to the people who DO manage the Smaug storage as a first step.

I think we would be better off focusing on the information we can get from within openshift without access to the backend. Because we don't manage the storage ourselves, any metrics that come directly from the backend would be of little use to us.

**Comment by hpdempsey** [comment]
Starting with OpenShift is OK.  I thought it was also possible to relate Ceph metrics to the OpenShift cluster...

**Comment by hpdempsey** [comment]
This project is completed.
