### ISSUE TITLE
Looking for suggestions on Co-op Project Idea

### ISSUE THREAD

**Issue by mubariskhan96** [operate-first/operations#446]
Hi there, 

I will be following @bryanmontalvan   project proposal template. ( Thanks Bryan!) 

### Introduction 
I will be working with the SRE team during my internship and I'm broadly interested in alerting and monitoring area. I'm looking at enhancing the alerts, monitoring capabilities within Operate First. My internship is going to be until June 10th, but I can leave some work for future also. So, I'm looking at doing a fairly big project that can be done in the next 5 months or more. 

### The Idea
After an insightful call with @HumairAK, I learnt about the areas in which alerting can be improved and what the current pain points are. The problem is, we're firing too many alerts and creating github issues from them. So, 

1. Identify the non-important alerts. 
2. Reduce the volume of alerts. 

And, on a related note, we were pondering if there's a better alternative to creating github issues for Alerts. The standard solution is to use Pagerduty but its a proprietary solution. And, I found [this](https://jayaj.medium.com/top-10-yellowant-integrations-f2e528310ec4) article which suggests there are indeed some open source alternatives to PagerDuty. 

In addition, I will also come up with the list of services deployed under Operate First and configure the alerts for those services. At this point, it is hard to estimate how many services or which services I can set alerts for. 

### Feedback 

I would like to invite feedback on:
 1. What are some other areas where alerting and monitoring can be improved?  Any other general advice that will make alerting / monitoring better? 
 2. Do you think is it a good idea to get rid of Github Issues for alerting and instead use one of the alternatives to pagerduty? 

Any pointers on how to plan this out better will also be greatly helpful! 

### Steps

- To be able to get a better understanding of how alerting is being used, [this](https://github.com/operate-first/SRE/issues/444) is a good first issue that I need to get started with. 
- After that, I will come up with a list of issues that are candidates of removal. To identify that, I would need to consult with the Subject Matter Experts and run the alert through the JUAN's principles and this should help in reducing the volume of alerts. This will be very valuable for the Operate First Project, in that 
- In the next phase of the project, I will be adding alerts to services in the operate first. There are many services in which we need to configure the alerts. And I will take, @4n4nd help in prioritizing the services and configuring the alerts on them. 

### Thinking 

I'm thinking to plan this out better before actually jumping into doing things. I will really appreciate insights from whoever is reading this. Any advice / suggestion will be helpful for me. Thanks! 

Updated Project: 

The last few weeks, after much deliberation, I realized that setting up alerts for services in operate first will be more valuable. And thus, I've kind of taken a detour from the initial project that I had planned on doing. However, it is still related to alerting. 

I will be adding alerts to services in the order of their importance. so that the "important" ( or more widely used) services are set up with alerts first and the list of the services is here[https://github.com/operate-first/apps/issues/1677](url)

**Comment by hpdempsey** [comment]
Firing too many alerts---the perennial monitoring issue.  This is a great area for your project Mubaris!  I think investigating alternatives to opening Github isseus for alerting is definitely a good idea.  Most ops groups I've worked with have had a tool like Nagios for managing and dispatching alerts that gives you more flexible options.  You would probably get involved some with defining our procedures for handling and escalating alerts too, just because you'd have to have these well defined to know what the tool you work on should be doing.  Having the procedures be better defined and more transparent would be useful too.

**Comment by HumairAK** [comment]
FYI: 
@larsks  @4n4nd @Gregory-Pereira

**Comment by Gregory-Pereira** [comment]
@HumairAK  I will take a look this afternoon. I will gather the links for code in Operate-First related to these projects for them.

**Comment by HumairAK** [comment]
@Gregory-Pereira I don't think you need to link any code/implementation for now. Rather just give your feedback/thoughts if you have any. Or, just be aware that this project exists :)
