### ISSUE TITLE
rename this repo to `operations`

### ISSUE THREAD

**Issue by durandom** [operate-first/operations#452]
Now that we have [sig-operations](https://github.com/operate-first/community/tree/main/sig-operations) and one subproject called operations, we could rename this repository to `operations` and free the name `sre` to 

* more generic content, i.e. not directly tied to operate the platform, like educational or best practices 
* more specific content, related to SRE and not operations in general

This is an area that @mmazur brought up in the sig-operations meeting

cc @quaid @jeremyeder @larsks @HumairAK

**Comment by HumairAK** [comment]
TBH I find the existince of this repo kind of confusing, can we just merge it with `apps` repo, and archive this one? Half the times we have issues being created her, and the other times it's in apps repo.

**Comment by larsks** [comment]
> TBH I find the existince of this repo kind of confusing, can we just merge it with apps repo, and archive this one?

Sometimes it's nice to have a place for issues that isn't tied to a particular codebase: e.g. for things like hardware problems ("node X is down due to a failed NIC") or software bugs that aren't directly tied to our YAML manifests ("Grafana bug is causing incorrect rendering of cpu graph"), etc.

**Comment by HumairAK** [comment]
Fair enough -- rename to `operations` then?

**Comment by larsks** [comment]
Sure. Or merge `SRE` with `support` and just call it `issues`.

**Comment by HumairAK** [comment]
I wonder how this works with peribolos, if I just rename [this](https://github.com/operate-first/common/blob/main/github-config.yaml#L88) will it delete the repo and create a new one called `operations`? Should I do it manually then send a pr in? @harshad16 do you or anyone else know?

**Comment by mmazur** [comment]
Does the PR require any further signoff and/or testing?

**Comment by HumairAK** [comment]
doone: https://github.com/operate-first/operations
