### ISSUE TITLE
Smaug OpenShift Cluster upgrade, Wednesday, February 23rd. 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#453]
Hello Operate First users,

The cluster-ops team will be upgrading the Smaug cluster from OCP 4.8 to OCP 4.9 on Wednesday, February 23rd.
We expect to start around 9:00-10:00AM EST. 

Related: 
- https://github.com/operate-first/apps/issues/1454

**Comment by HumairAK** [comment]
Upgrade resumed with admin ack.

**Comment by HumairAK** [comment]
There is a node stuck at drain stage that has halted the upgrade process.

**Comment by HumairAK** [comment]
The events were not very descriptive the for the `node` in question. But the `machine-config-daemon` in the `openshift-machine-config-operator` namespace, that was deployed on this node offered the root cause: 
```
I0414 13:47:10.214862 1899829 daemon.go:334] evicting pod openshift-image-registry/image-registry-75ff6bd654-t9725
E0414 13:47:10.224967 1899829 daemon.go:334] error when evicting pods/"image-registry-75ff6bd654-t9725" -n "openshift-image-registry" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
I0414 13:47:15.226279 1899829 daemon.go:334] evicting pod openshift-image-registry/image-registry-75ff6bd654-t9725
E0414 13:47:15.235319 1899829 daemon.go:334] error when evicting pods/"image-registry-75ff6bd654-t9725" -n "openshift-image-registry" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
I0414 13:47:17.598660 1899829 update.go:1904] Removing SIGTERM protection
E0414 13:47:17.598739 1899829 writer.go:135] Marking Degraded due to: failed to drain node : oct-03-01-compute after 1 hour
```

Deleting this pod resolved the issue.

**Comment by HumairAK** [comment]
> seems like the node is now stuck on the os upgrading stage

```
E0414 14:32:00.105224 1899829 writer.go:135] Marking Degraded due to: failed to update OS to quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08d376c06b2acc8ad4abf4527aabd24922c4e2a3cc8834dd0b9c8d63fff4e3f4 : error running rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-080594765/srv/repo:d4bb9737c5139799bd9d855853a42f5bc83cfa5acdd6ff9d0f0d90ceee9a36ae --custom-origin-url pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08d376c06b2acc8ad4abf4527aabd24922c4e2a3cc8834dd0b9c8d63fff4e3f4 --custom-origin-description Managed by machine-config-operator: error: Transaction in progress: (null)
: exit status 1
```

From the machine-config-daemon above. 

~ $ oc get node oct-03-01-compute -o yaml | yq .metadata.annotations

```
~ $ oc get node oct-03-01-compute -o yaml | yq .metadata.annotations
...
machineconfiguration.openshift.io/reason: |-
  failed to update OS to quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08d376c06b2acc8ad4abf4527aabd24922c4e2a3cc8834dd0b9c8d63fff4e3f4 : error running rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-200142989/srv/repo:d4bb9737c5139799bd9d855853a42f5bc83cfa5acdd6ff9d0f0d90ceee9a36ae --custom-origin-url pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08d376c06b2acc8ad4abf4527aabd24922c4e2a3cc8834dd0b9c8d63fff4e3f4 --custom-origin-description Managed by machine-config-operator: error: Transaction in progress: (null)
  : exit status 1
machineconfiguration.openshift.io/ssh: accessed
machineconfiguration.openshift.io/state: Degraded

~ $ 

```

**Comment by HumairAK** [comment]
support case created: https://access.redhat.com/support/cases/#/case/03197956

**Comment by HumairAK** [comment]
Rebooting the machine config daemon seems to have pushed the node past the os upgrade stage: 

```
~ $ oc delete pods machine-config-daemon-xfmhg -n openshift-machine-config-operator 
pod "machine-config-daemon-xfmhg" deleted
```

Logs from the daemon pod: 

<details>
<summary> logs </summary>
I0414 18:37:58.882520 3959014 rpm-ostree.go:297] Executing rebase from repo path /run/mco-machine-os-content/os-content-342990518/srv/repo with customImageURL pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08d376c06b2acc8ad4abf4527aabd24922c4e2a3cc8834dd0b9c8d63fff4e3f4 and checksum d4bb9737c5139799bd9d855853a42f5bc83cfa5acdd6ff9d0f0d90ceee9a36ae
I0414 18:37:58.882541 3959014 update.go:1859] Running: rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-342990518/srv/repo:d4bb9737c5139799bd9d855853a42f5bc83cfa5acdd6ff9d0f0d90ceee9a36ae --custom-origin-url pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08d376c06b2acc8ad4abf4527aabd24922c4e2a3cc8834dd0b9c8d63fff4e3f4 --custom-origin-description Managed by machine-config-operator
1133 metadata, 3846 content objects imported; 1.1 GB content written
Writing objects: 19...done
Staging deployment...done
Freed: 886.7 MB (pkgcache branches: 0)
Upgraded:
  afterburn 5.0.0-1.rhaos4.8.el8 -> 5.1.0-1.rhaos4.9.el8
  bootupd 0.2.5-2.el8 -> 0.2.5-3.rhaos4.9.el8
  console-login-helper-messages 0.20.3-1.rhaos4.8.el8 -> 0.20.3-1.rhaos4.9.el8
  console-login-helper-messages-issuegen 0.20.3-1.rhaos4.8.el8 -> 0.20.3-1.rhaos4.9.el8
  console-login-helper-messages-profile 0.20.3-1.rhaos4.8.el8 -> 0.20.3-1.rhaos4.9.el8
  coreos-installer 0.9.0-8.rhaos4.8.el8 -> 0.10.1-1.rhaos4.9.el8
  coreos-installer-bootinfra 0.9.0-8.rhaos4.8.el8 -> 0.10.1-1.rhaos4.9.el8
  cri-o 1.21.4-4.rhaos4.8.git84fa55d.el8 -> 1.22.1-14.rhaos4.9.git7486bc8.el8
  cri-tools 1.21.0-3.el8 -> 1.22.0-1.el8
  device-mapper-multipath 0.8.4-10.el8 -> 0.8.4-10.el8_4.2
  device-mapper-multipath-libs 0.8.4-10.el8 -> 0.8.4-10.el8_4.2
  ignition 2.9.0-7.rhaos4.8.el8 -> 2.12.0-2.rhaos4.9.el8
  kernel 4.18.0-305.28.1.el8_4 -> 4.18.0-305.34.2.el8_4
  kernel-core 4.18.0-305.28.1.el8_4 -> 4.18.0-305.34.2.el8_4
  kernel-modules 4.18.0-305.28.1.el8_4 -> 4.18.0-305.34.2.el8_4
  kernel-modules-extra 4.18.0-305.28.1.el8_4 -> 4.18.0-305.34.2.el8_4
  kexec-tools 2.0.20-46.el8_4.2 -> 2.0.20-46.el8_4.3
  kpartx 0.8.4-10.el8 -> 0.8.4-10.el8_4.2
  libibverbs 32.0-4.el8 -> 32.0-5.el8_4
  libsmbclient 4.13.3-5.el8_4 -> 4.13.3-9.el8_4
  libwbclient 4.13.3-5.el8_4 -> 4.13.3-9.el8_4
  openshift-clients 4.8.0-202109201328.p0.git.88e7eba.assembly.stream.el8 -> 4.9.0-202202080146.p0.g52a2fd9.assembly.stream.el8
  openshift-hyperkube 4.8.0-202111251824.p0.g935ba91.assembly.stream.el8 -> 4.9.0-202202031036.p0.gfdba464.assembly.stream.el8
  openvswitch2.15 2.15.0-38.el8fdp -> 2.15.0-55.el8fdp
  ostree 2020.7-5.el8_4 -> 2020.7-6.el8_4
  ostree-grub2 2020.7-5.el8_4 -> 2020.7-6.el8_4
  ostree-libs 2020.7-5.el8_4 -> 2020.7-6.el8_4
  polkit 0.115-11.el8_4.1 -> 0.115-11.el8_4.2
  polkit-libs 0.115-11.el8_4.1 -> 0.115-11.el8_4.2
  rdma-core 32.0-4.el8 -> 32.0-5.el8_4
  redhat-release-coreos 48.84-4.el8 -> 49.84-2.el8
  rpm 4.14.3-14.el8_4 -> 4.14.3-14.el8_4.2
  rpm-libs 4.14.3-14.el8_4 -> 4.14.3-14.el8_4.2
  rpm-plugin-selinux 4.14.3-14.el8_4 -> 4.14.3-14.el8_4.2
  samba-client-libs 4.13.3-5.el8_4 -> 4.13.3-9.el8_4
  samba-common 4.13.3-5.el8_4 -> 4.13.3-9.el8_4
  samba-common-libs 4.13.3-5.el8_4 -> 4.13.3-9.el8_4
  selinux-policy 3.14.3-67.el8_4.2 -> 3.14.3-67.el8_4.4
  selinux-policy-targeted 3.14.3-67.el8_4.2 -> 3.14.3-67.el8_4.4
  subscription-manager-rhsm-certificates 1.28.13-4.el8_4 -> 1.28.13-6.el8_4
  systemd 239-45.el8_4.3 -> 239-45.el8_4.6
  systemd-journal-remote 239-45.el8_4.3 -> 239-45.el8_4.6
  systemd-libs 239-45.el8_4.3 -> 239-45.el8_4.6
  systemd-pam 239-45.el8_4.3 -> 239-45.el8_4.6
  systemd-udev 239-45.el8_4.3 -> 239-45.el8_4.6
  toolbox 0.0.8-3.rhaos4.8.el8 -> 0.0.8-3.rhaos4.9.el8
Downgraded:
  container-selinux 2:2.170.0-2.rhaos4.8.el8 -> 2:2.167.0-1.module+el8.4.0+12646+b6fd1bdf
  perl-Carp 1.50-439.module+el8.3.0+6718+7f269185 -> 1.42-396.el8
  perl-Data-Dumper 2.174-440.module+el8.3.0+6718+7f269185 -> 2.167-399.el8
  perl-Digest 1.17-396.module+el8.3.0+6718+7f269185 -> 1.17-395.el8
  perl-Digest-MD5 2.55-397.module+el8.3.0+6718+7f269185 -> 2.55-396.el8
  perl-Encode 4:3.01-439.module+el8.3.0+6718+7f269185 -> 4:2.97-3.el8
  perl-Errno 1.30-452.module+el8.4.0+8990+01326e37 -> 1.28-419.el8_4.1
  perl-Exporter 5.73-440.module+el8.3.0+6718+7f269185 -> 5.72-396.el8
  perl-File-Path 2.16-439.module+el8.3.0+6718+7f269185 -> 2.15-2.el8
  perl-File-Temp 1:0.230.900-439.module+el8.3.0+6718+7f269185 -> 0.230.600-1.el8
  perl-Getopt-Long 1:2.51-1.module+el8.3.0+6718+7f269185 -> 1:2.50-4.el8
  perl-HTTP-Tiny 0.076-439.module+el8.3.0+6718+7f269185 -> 0.074-1.el8
  perl-IO 1.40-452.module+el8.4.0+8990+01326e37 -> 1.38-419.el8_4.1
  perl-IO-Socket-IP 0.39-6.module+el8.3.0+6718+7f269185 -> 0.39-5.el8
  perl-IO-Socket-SSL 2.066-4.module+el8.3.0+6452+449fe210 -> 2.066-4.el8
  perl-MIME-Base64 3.15-1001.module+el8.3.0+6718+7f269185 -> 3.15-396.el8
  perl-Mozilla-CA 20160104-7.module+el8.3.0+6498+fb59cb73 -> 20160104-7.el8
  perl-Net-SSLeay 1.88-1.module+el8.3.0+6452+449fe210 -> 1.88-1.el8
  perl-PathTools 3.78-439.module+el8.3.0+6718+7f269185 -> 3.74-1.el8
  perl-Pod-Escapes 1:1.07-396.module+el8.3.0+6718+7f269185 -> 1:1.07-395.el8
  perl-Pod-Perldoc 3.28.01-442.module+el8.3.0+6718+7f269185 -> 3.28-396.el8
  perl-Pod-Simple 1:3.40-1.module+el8.3.0+6718+7f269185 -> 1:3.35-395.el8
  perl-Pod-Usage 4:1.69-396.module+el8.3.0+6718+7f269185 -> 4:1.69-395.el8
  perl-Scalar-List-Utils 3:1.53-439.module+el8.3.0+6718+7f269185 -> 3:1.49-2.el8
  perl-Socket 4:2.029-4.module+el8.3.0+6718+7f269185 -> 4:2.027-3.el8
  perl-Storable 1:3.15-442.module+el8.3.0+6718+7f269185 -> 1:3.11-3.el8
  perl-Term-ANSIColor 4.06-397.module+el8.3.0+6718+7f269185 -> 4.06-396.el8
  perl-Term-Cap 1.17-396.module+el8.3.0+6718+7f269185 -> 1.17-395.el8
  perl-Text-ParseWords 3.30-396.module+el8.3.0+6718+7f269185 -> 3.30-395.el8
  perl-Text-Tabs+Wrap 2013.0523-396.module+el8.3.0+6718+7f269185 -> 2013.0523-395.el8
  perl-Time-Local 1:1.280-2.module+el8.3.0+6718+7f269185 -> 1:1.280-1.el8
  perl-URI 1.76-5.module+el8.3.0+6718+7f269185 -> 1.73-3.el8
  perl-Unicode-Normalize 1.26-439.module+el8.3.0+6718+7f269185 -> 1.25-396.el8
  perl-constant 1.33-1001.module+el8.3.0+6718+7f269185 -> 1.33-396.el8
  perl-interpreter 4:5.30.1-452.module+el8.4.0+8990+01326e37 -> 4:5.26.3-419.el8_4.1
  perl-libnet 3.11-4.module+el8.3.0+6718+7f269185 -> 3.11-3.el8
  perl-libs 4:5.30.1-452.module+el8.4.0+8990+01326e37 -> 4:5.26.3-419.el8_4.1
  perl-macros 4:5.30.1-452.module+el8.4.0+8990+01326e37 -> 4:5.26.3-419.el8_4.1
  perl-parent 1:0.237-2.module+el8.3.0+6718+7f269185 -> 1:0.237-1.el8
  perl-podlators 1:4.12-2.module+el8.3.0+6718+7f269185 -> 4.11-1.el8
  perl-threads 1:2.22-439.module+el8.3.0+6718+7f269185 -> 1:2.21-2.el8
  perl-threads-shared 1.60-440.module+el8.3.0+6718+7f269185 -> 1.58-2.el8
  runc 1.0.0-98.rhaos4.8.gitcd80260.el8 -> 1.0.0-74.rc95.module+el8.4.0+11822+6cc1e7d7
Removed:
  bind-export-libs-32:9.11.26-4.el8_4.x86_64
  dhcp-client-12:4.3.6-44.el8_4.1.x86_64
  dhcp-common-12:4.3.6-44.el8_4.1.noarch
  dhcp-libs-12:4.3.6-44.el8_4.1.x86_64
  ipcalc-0.2.4-4.el8.x86_64
Run "systemctl reboot" to start a reboot
I0414 18:38:08.266460 3959014 update.go:1874] Rebooting node
I0414 18:38:08.273343 3959014 update.go:1904] Removing SIGTERM protection
I0414 18:38:08.273404 3959014 update.go:1874] initiating reboot: Node will reboot into config rendered-worker-d9f9c99c732c6cdc4d96626cae2c0d6c


</details>

**Comment by HumairAK** [comment]
The cluster upgrade has moved on from this node and onto the next

**Comment by larsks** [comment]
The cluster upgrade got stuck (again!) because it was unable to drain `oct-03-12-compute`:

```
error when evicting pods/"odh-message-bus-kafka-2" -n "opf-kafka" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

I deleted the blocking pod and the ugprade has moved on to the next step.

**Comment by larsks** [comment]
Pod `prometheus-k8s-0` is is trying to mount volume `pvc-301fb2d3-4a1c-4ecc-b1eb-e1e4e73a5e1c`, which came from the NFS server. That server is no longer available.

**Comment by larsks** [comment]
I have deleted the NFS PV and allowed the monitoring stack to create a new PVC and now prometheus has started successfully.

**Comment by larsks** [comment]
The upgrade to 4.9.21 has completed successfully.

```
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.9.21    True        False         2d2h    Cluster version is 4.9.21
```
