### ISSUE TITLE
[INCIDENT][SMAUG/CI-PROW] - CI PROW Fails due to storages issue

### ISSUE THREAD

**Issue by harshad16** [operate-first/operations#454]
### Clusters Affected

smaug

### Users Affected

Users using ci prow on the Github repos. 
Organizations affected:
- Open-services-group
- AICoE
- Operate-first
- AICoE-AIOps
- Thoth-station

### Incident Description

Hello Operate First Users,

we are investigating an ongoing incident affecting CI prow which is deployed on smaug cluster

we will provide updates to this issue thread as the incident progresses.

### Relevant Links

The storage seems to be affected, causing hinder is prow job runs.
![nooba-prow-error](https://user-images.githubusercontent.com/14028058/155353270-0bdeb85d-8cf3-4245-bfe9-33f7078e8fab.png)
![prow](https://user-images.githubusercontent.com/14028058/155353272-756574b9-ea81-4f7d-8909-cc3f8242b3fc.png)

**Comment by harshad16** [comment]
We have temporarily fixed the CI
user can type `/retest` to execute the CI.

Keeping the issue open, as this is just a temporary solution

**Comment by HumairAK** [comment]
Support case here for noobaa issues on smaug : https://access.redhat.com/support/cases/#/case/03158868

**Comment by rbo** [comment]
The detail page of tests, for [example](https://prow.operate-first.cloud/view/s3/thoth/prow-logs/pr-logs/pull/operate-first_hetzner-baremetal-openshift/17/pre-commit/1497115627624599552) delivers a  504 Gateway Time-out. It this related to this issue?

**Comment by harshad16** [comment]
> The detail page of tests, for [example](https://prow.operate-first.cloud/view/s3/thoth/prow-logs/pr-logs/pull/operate-first_hetzner-baremetal-openshift/17/pre-commit/1497115627624599552) delivers a 504 Gateway Time-out. It this related to this issue?

@rbo , please run retest once more, we have fixed it now.

**Comment by harshad16** [comment]
This is fixed and thanks to everyone, who has worked on this.
