### ISSUE TITLE
Add apirequestcount read permissions to sre group in smaug/infra

### ISSUE THREAD

**Issue by dystewart** [operate-first/operations#455]
@HumairAK I currently have the cluster-view role but I need higher permissions to be able to access certain commands such as `oc get apirequestcounts` and to view other resources like secrets in the Smaug cluster.

**Comment by HumairAK** [comment]
@dystewart can you create a `clusterrole` and `clusterrolebinding` that gives read permissions to the `sre` group and add this to the `cluster-scope` base repo and also deploy it in `smaug` and the other clusters?

**Comment by dystewart** [comment]
@HumairAK Including clusters like the osc clusters?

**Comment by HumairAK** [comment]
hmm good question... leave those clusters for now, update only the ones that include the sre group.
