### ISSUE TITLE
Mailman is offline

### ISSUE THREAD

**Issue by larsks** [operate-first/operations#457]
Trying to access the mailman ui at <https://lists.operate-first.cloud/admin/lists/community.lists.operate-first.cloud/> results in this error:

> Something went wrong
>
> Mailman REST API not available. Please start Mailman core.

**Comment by quaid** [comment]
@mscherer the monitoring on this page hasn't seemed to signal the service being down, so you probably aren't getting alerts.

https://osci.io/tenants/

Ultimately, it's also a problem that no one other than me knows who to contact about issues with lists.operate-first.cloud. I'd like to open an issue to see that worked out, should I do that here in github://operate-first/operations or github://operate-first/support?

**Comment by mscherer** [comment]
no, the problem was resolved. We had a physical server issue (not sure of the date), and after restart, half of the mailman servers didn't start correctly. But the monitoring didn't detect that (I think @duck-rh is looking at that).
