### ISSUE TITLE
Decommission Rick Cluster

### ISSUE THREAD

**Issue by dystewart** [operate-first/operations#469]
We need to Decommission the Rick cluster so we need to:

- [x] Confirm nothing is running on Rick
- [x] Migrate argocd apps currently deploying in Rick to deploy in Morty 
- [x] Offboard Rick according to these [cluster offboarding docs](https://www.operate-first.cloud/apps/content/cluster-scope/offboarding_cluster.html)
- [x] Make any necessary changes or updates to [cluster offboarding docs](https://www.operate-first.cloud/apps/content/cluster-scope/offboarding_cluster.html)
 - [ ] Bring down Rick OCP cluster

**Comment by dystewart** [comment]
@HumairAK It looks as though the only workloads running on Rick are a few operators (ESO, ACME, Kafka) and the default OpenShift services. 

I also checked in with @4n4nd and @harshad16 to verify that the cluster was ready for decommissioning

Going to use the docs linked above to get started

**Comment by harshad16** [comment]
The rick cluster argocd applications are removed 
and rick cluster is detached from rhacm.

Things left to be done:
- [ ]  update the docs with respect to rick to morty
- [ ] Other components having rick needs update as well(like observatorium , kafka )

**Comment by harshad16** [comment]
oh that what i meant from my second point :smile:

**Comment by rbo** [comment]
Power off all nodes in hetzner console.

**Comment by rbo** [comment]
ToDos:
 - [ ] Cancel the servers
 - [ ] Remove DNS Records

**Comment by rbo** [comment]
Servers are down, start Cancellation

**Comment by rbo** [comment]
- [X] Server canceled
- [X] DNS Recordes delete
- [X] Hetzner Cloud LB & VM deleted.

**Comment by rbo** [comment]
From my point of view. We are done...
