### ISSUE TITLE
[INCIDENT][Morty] - Morty is currently down

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/operations#490]
### Clusters Affected

Morty

### Users Affected

all of EMEA using morty

### Incident Description

Hello Operate-first Users,

The morty cluster is currently down. We will be updating you with more information is available.

### Relevant Links

https://console-openshift-console.apps.morty.emea.operate-first.cloud/

/cc @rbo

**Comment by rbo** [comment]
```
$ ping morty-router-a.emea.operate-first.cloud 
PING morty-router-a.emea.operate-first.cloud(2a01:4f8:140:23dc::2 (2a01:4f8:140:23dc::2)) 56 data bytes
^C
--- morty-router-a.emea.operate-first.cloud ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3074ms

$ ping -4 morty-router-a.emea.operate-first.cloud 
PING  (46.4.65.182) 56(84) bytes of data.
^C
---  ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1039ms

$ 
```

Router of morty is offline.

**Comment by rbo** [comment]
Send CTRL+ALT+DEL to the server via hetzner managment ui

**Comment by rbo** [comment]
CTRL+ALT+DEL, doesn't solve the problem. 

Execute an automatic hardware reset

**Comment by rbo** [comment]
Created a ticket for remote console access

**Comment by rbo** [comment]
Requested for 10 AM 2022-08-03 - gn8

**Comment by rbo** [comment]
From hetznzer:
> the server is inaccessible because your servers have been locked because of an unpaid invoice. The system itself should be fine.

@durandom please have a look, it looks like the hetzner bills are not paid.

**Comment by durandom** [comment]
@rbo indeed, there's a hickup in the procurement pipeline. Working on it

**Comment by Gregory-Pereira** [comment]
Morty is currently accessible again. Can someone confirm we can close this incedent?

**Comment by rbo** [comment]
If it works for you of curse.

**Comment by HumairAK** [comment]
@rbo morty is still inaccessible for me and others

**Comment by Gregory-Pereira** [comment]
unsure why, can someone share information on how it is inaccessible, or what information they get back? For reference I am connecting without the VPN from NA. My logs: 
```
$ oc login --token=<TOKEN_REDACTED> --server=https://api.morty.emea.operate-first.cloud:6443
Logged into "https://api.morty.emea.operate-first.cloud:6443" as "Gregory-Pereira" using the token provided.
You have access to ...
Using project "openshift-storage".
$ oc get nodes
NAME                                               STATUS   ROLES          AGE    VERSION
morty-compute-0-private.emea.operate-first.cloud   Ready    worker         164d   v1.22.3+fdba464
morty-compute-1-private.emea.operate-first.cloud   Ready    worker         164d   v1.22.3+fdba464
morty-compute-2-private.emea.operate-first.cloud   Ready    worker         164d   v1.22.3+fdba464
morty-master-0-private.emea.operate-first.cloud    Ready    master         164d   v1.22.3+fdba464
morty-master-1-private.emea.operate-first.cloud    Ready    master         164d   v1.22.3+fdba464
morty-master-2-private.emea.operate-first.cloud    Ready    master         164d   v1.22.3+fdba464
morty-storage-0-private.emea.operate-first.cloud   Ready    infra,worker   164d   v1.22.3+fdba464
morty-storage-1-private.emea.operate-first.cloud   Ready    infra,worker   164d   v1.22.3+fdba464
morty-storage-2-private.emea.operate-first.cloud   Ready    infra,worker   164d   v1.22.3+fdba464
```

**Comment by HumairAK** [comment]
It seems to be working now, further discussion on decommissioning can take place here: https://github.com/operate-first/operations/issues/491
